export const ADD_COMPANY_SERVICE_ICON_RIGHT_POSITION = -400;
export const ADD_COMPANY_SERVICE_ICON_BOTTOM_POSITION = 70;

export const ADD_COMPANY_SERVICE_DURATION_WIDTH = "50%";
export const ADD_COMPANY_SERVICE_PRICE_WIDTH = "50%";

export const MIN_SERVICE_DURATION_MINUTES = 15;
