export const ADD_COMPANY_SERVICE_TITTLE_WIDTH = "70%";
export const ADD_COMPANY_SERVICE_PRICE_WIDTH = "30%";

export const ADD_COMPANY_ICON_RIGHT_POSITION = -400;
export const ADD_COMPANY_ICON_BOTTOM_POSITION = 50;
